name: "Create docker image."

on:
    push:
        branches:
         - main
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
     - uses: actions/checkout@v4

     - name: Create Dcoker image.
       run: echo "Testing workflow file..."