name: "Create docker image."

on:
    push:
        branches:
         - main
         - docker

    
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
     - uses: actions/checkout@v4

     - name: Setup QEMU.
       uses: docker/setup-qemu-action@v3

     - name: Setup Docker buildx.
       uses: docker/setup-buildx-action@v3

     - name: Create Docker image.
       uses: docker/build-push-action@v5
       with:
         context: .
         push: false
         tags: app:latest